<?xml version="1.0" encoding="utf-8"?>

<Database Name="aspnet-ProStudCreator-20140818043155" Class="ProStudentCreatorDBDataContext"
          xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings"
              ConnectionString="Data Source=FLAVIOLAPTOP;Initial Catalog=aspnet-ProStudCreator-20140818043155;Integrated Security=True"
              SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings"
              SettingsPropertyName="aspnet_ProStudCreator_20140818043155ConnectionString"
              Provider="System.Data.SqlClient" />
  <Table Name="dbo.Departments" Member="Departments">
    <Type Name="Department">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="OUCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShowDefenseOnInfoPage" Type="System.Boolean" DbType="bit" CanBeNull="false" />
      <Column Name="IMVS" Type="System.Boolean" DbType="bit" CanBeNull="false" />
      <Column Name="i4DS" Type="System.Boolean" DbType="bit" CanBeNull="false" />
      <Association Name="Department_Project" Member="Projects" ThisKey="Id" OtherKey="DepartmentId" Type="Project" />
      <Association Name="Department_UserDepartmentMap" Member="UserDepartmentMap" ThisKey="Id" OtherKey="DepartmentId"
                   Type="UserDepartmentMap" />
    </Type>
  </Table>
  <Table Name="dbo.ProjectTeamSize" Member="ProjectTeamSizes">
    <Type Name="ProjectTeamSize">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Size1" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Size2" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ExportValue" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ProjectTeamSize_Project" Member="Projects" ThisKey="Id" OtherKey="P1TeamSizeId" Type="Project" />
      <Association Name="ProjectTeamSize_Project1" Member="Projects1" ThisKey="Id" OtherKey="P2TeamSizeId"
                   Type="Project" />
    </Type>
  </Table>
  <Table Name="dbo.ProjectTypes" Member="ProjectTypes">
    <Type Name="ProjectType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P5" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="P6" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ExportValue" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ProjectType_Project" Member="Projects" ThisKey="Id" OtherKey="P1TypeId" Type="Project" />
      <Association Name="ProjectType_Project1" Member="Projects1" ThisKey="Id" OtherKey="P2TypeId" Type="Project" />
      <Association Name="ProjectType_Project2" Member="Project" ThisKey="Id" OtherKey="LogProjectTypeID" Type="Project" />
    </Type>
  </Table>
  <Table Name="dbo.Experts" Member="Experts">
    <Type Name="Expert">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Unternehmen" Type="System.String" DbType="varchar(100)" CanBeNull="true" />
      <Association Name="Expert_Project" Member="Projects" ThisKey="id" OtherKey="LogExpertID" Type="Project" />
    </Type>
  </Table>
  <Table Name="dbo.BillingStatus" Member="BillingStatus">
    <Type Name="BillingStatus">
      <Column Name="Id" Storage="_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true"
              IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShowAddressOnInfoPage" Type="System.Boolean" DbType="bit" CanBeNull="false" />
      <Association Name="BillingStatus_Project" Member="Projects" ThisKey="Id" OtherKey="BillingStatusID"
                   Type="Project" />
    </Type>
  </Table>
  <Table Name="dbo.Projects" Member="Projects">
    <Type Name="Project">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Creator" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ClientCompany" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ClientPerson" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ClientMail" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Advisor1Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Advisor2Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Advisor1Mail" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Advisor2Mail" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TypeDesignUX" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TypeHW" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TypeCGIP" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TypeMathAlg" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TypeAppWeb" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TypeDBBigData" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="P1TypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="P1TeamSizeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="P2TypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="P2TeamSizeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InitialPosition" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never"
              IsDelayLoaded="true" />
      <Column Name="Objective" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ProblemStatement" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[References]" Member="References" Type="System.String" DbType="NVarChar(MAX) NOT NULL"
              CanBeNull="false" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Reservation1Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Reservation1Mail" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Reservation2Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Reservation2Mail" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Important" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OverOnePage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModificationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PublishedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastEditedBy" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ProjectNr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LanguageGerman" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LanguageEnglish" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DurationOneSemester" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TypeSysSec" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TypeSE" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ImgDescription" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IsContinuation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PreviousProjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClientAddressStreet" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ClientAddressPostcode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ClientAddressCity" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BillingStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogProjectTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogProjectDuration" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="LogStudent1Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LogStudent1Mail" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LogStudent2Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LogStudent2Mail" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LogExpertID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogExpertPaid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LogDefenceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LogDefenceRoom" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="SemesterId" Storage="_SemersterId" Type="System.Int32" DbType="int" CanBeNull="true" />
      <Column Name="LogGradeStudent1" Storage="_LogGrade" Type="System.Single" DbType="float" CanBeNull="true" />
      <Column Name="LogLanguageEnglish" Type="System.Boolean" DbType="bit" CanBeNull="true" />
      <Column Name="LogLanguageGerman" Type="System.Boolean" DbType="bit" CanBeNull="true" />
      <Column Name="ClientAddressTitle" Type="System.String" DbType="varchar(30)" CanBeNull="true" />
      <Column Name="ClientAddressDepartment" Type="System.String" DbType="varchar(50)" CanBeNull="true" />
      <Column Name="ClientReferenceNumber" Type="System.String" DbType="varchar(50)" CanBeNull="true" />
      <Column Name="LogGradeStudent2" Type="System.Single" DbType="float" CanBeNull="true" />
      <Association Name="Project_Project" Member="Projects" ThisKey="Id" OtherKey="PreviousProjectID" Type="Project" />
      <Association Name="Project_Attachements" Member="Attachements" ThisKey="Id" OtherKey="ProjectId"
                   Type="Attachements" />
      <Association Name="BillingStatus_Project" Member="BillingStatus" ThisKey="BillingStatusID" OtherKey="Id"
                   Type="BillingStatus" IsForeignKey="true" />
      <Association Name="Expert_Project" Member="Expert" ThisKey="LogExpertID" OtherKey="id" Type="Expert"
                   IsForeignKey="true" />
      <Association Name="Project_Project" Member="Project1" ThisKey="PreviousProjectID" OtherKey="Id" Type="Project"
                   IsForeignKey="true" />
      <Association Name="Department_Project" Member="Department" ThisKey="DepartmentId" OtherKey="Id" Type="Department"
                   IsForeignKey="true" />
      <Association Name="ProjectType_Project" Member="POneType" ThisKey="P1TypeId" OtherKey="Id" Type="ProjectType"
                   IsForeignKey="true" />
      <Association Name="ProjectType_Project1" Member="PTwoType" ThisKey="P2TypeId" OtherKey="Id" Type="ProjectType"
                   IsForeignKey="true" />
      <Association Name="ProjectTeamSize_Project" Member="POneTeamSize" ThisKey="P1TeamSizeId" OtherKey="Id"
                   Type="ProjectTeamSize" IsForeignKey="true" />
      <Association Name="ProjectTeamSize_Project1" Member="PTwoTeamSize" ThisKey="P2TeamSizeId" OtherKey="Id"
                   Type="ProjectTeamSize" IsForeignKey="true" />
      <Association Name="Semester_Project" Member="Semester" Storage="_Semesters" ThisKey="SemesterId" OtherKey="Id"
                   Type="Semester" IsForeignKey="true" />
      <Association Name="ProjectType_Project2" Member="LogProjectType" ThisKey="LogProjectTypeID" OtherKey="Id"
                   Type="ProjectType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="Semester">
    <Type Name="Semester">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="ProjectSubmissionUntil" Storage="_ProjectSubmit" Type="System.DateTime" DbType="DateTime"
              CanBeNull="false" />
      <Column Name="ProjectAllocation" Type="System.String" DbType="NVarChar(50)" CanBeNull="false" />
      <Column Name="SubmissionIP5FullPartTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="false" />
      <Column Name="SubmissionIP5Accompanying" Type="System.String" DbType="NVarChar(50)" CanBeNull="false" />
      <Column Name="SubmissionIP6Normal" Type="System.String" DbType="NVarChar(50)" CanBeNull="false" />
      <Column Name="SubmissionIP6Variant2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DefenseIP6Start" Storage="_DefenseIP6" Type="System.String" DbType="NVarChar(50)" CanBeNull="false" />
      <Column Name="DefenseIP6End" Storage="_DefenseIP6Alternative" Type="System.String" DbType="NVarChar(50)"
              CanBeNull="false" />
      <Column Name="ExhibitionBachelorThesis" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="nchar(4)" CanBeNull="false" />
      <Column Name="SemesterActiveUntil" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DefenseIP6BStart" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DefenseIP6BEnd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Semester_Project" Member="Project" ThisKey="Id" OtherKey="SemesterId" Type="Project" />
    </Type>
  </Table>
  <Table Name="dbo.Attachements" Member="Attachements">
    <Type Name="Attachements">
      <Column Name="ROWGUID" AutoSync="Never" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true"
              IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectAttachement" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true"
              UpdateCheck="Never" IsDelayLoaded="true" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UploadUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UploadDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UploadSize" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DeletedUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Project_Attachements" Member="Project" ThisKey="ProjectId" OtherKey="Id" Type="Project"
                   IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserDepartmentMap" Member="UserDepartmentMap">
    <Type Name="UserDepartmentMap">
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CanExportExcel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanPublishProject" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanVisitAdminPage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanSeeAllProjectsInProgress" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanEditAllProjects" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanSubmitAllProjects" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanSeeCreationDetails" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Department_UserDepartmentMap" Member="Department" ThisKey="DepartmentId" OtherKey="Id"
                   Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
</Database>